services:
  database:
    image: "postgres"
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dreilacadin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scentlog_db
  test_db:
    image: "postgres"
    restart: always
    ports:
      - 5433:5432
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dreilacadin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scentlog_db_test
volumes:
  pgdata:
  pgdata_test: